language: python
python: 3.6
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
  - PLONE_VERSION=5.2
matrix:
  fast_finish: true
install:
  - sed -ie "s#test-5.2.cfg#test-$PLONE_VERSION.cfg#" buildout.cfg
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage -t "--layer=!Robot"
  - pip install --upgrade coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
